# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06908bd79e4eeba16fa120556794198a66711ea438ba3342034dc1723b4ee5e093f356edff9eb4a15ee3e1cf0100d4b469f405dcd6f48ab80117dd6054b79f9

test:
  secret_key_base: a2e96d16268c92f3fa6718704ac998572a40c738e63291acd7b17490204319678fb44bf8b8ecccf53bcf1aa7d8e0e8f9103b9ece9cfbf5e2c502f6db752d9cc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
